flags:
  buildsome:
    Charts: False
packages:
- location: https://github.com/da-x/happy/archive/65c2494c77bd1bb321c1eb29b5117a975b1723a0.zip
  extra-dep: true
- .
extra-deps:
- leveldb-haskell-0.6.3
resolver: lts-8.17
rebuild-ghc-options: true
